# Reference: https://www.appveyor.com/docs/appveyor-yml/
# Validation:
# $ ruby -ryaml -e 'puts (YAML.load_file "appveyor.yml")["script"]'

# Version format. We don't use this, so let it just be less confusing on UI.
version: "#{build}"

environment:
  FLUTTER_SDK_ROOT: "C:\\flutter"
  PATH: "C:\\Ruby22-x64\\bin;%FLUTTER_SDK_ROOT%\\bin;%PATH%"
  ANDROID_SDK_ROOT: "C:\\Android\\Sdk"
  ANDROID_HOME: "%ANDROID_SDK_ROOT%"

install:
  - ruby -v
  - gem -v
  - bundle -v
  - bundle install --deployment
  - git clone -b master https://github.com/flutter/flutter.git C:\flutter
  - copy tools\ci\google-services.json flutter\android\app\google-services.json
  #- md "%USERPROFILE%\\.android"
  - copy tools\ci\debug.keystore "%USERPROFILE%\\.android"

build: off

build_script:
  - cd flutter
  - cmd.exe /c bundle exec fastlane android build `>log.txt 2`>`&1
  - cd android
  - gradlew dependencies
  - flutter build apk --debug

before_test:
  - ruby -v
  - gem -v
  - bundle -v

test_script:
  - bundle exec fastlane ensure_clean_git

#branches:
#  only:
#    - master
#    - gssoc19
